version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true
  python-isort: &python-isort
    format-command: 'isort --quiet --profile black -'
    format-stdin: true
languages:
  python:
    - <<: *python-isort
    - <<: *python-black

