vim.keymap.set("n", "<F5>", require('dap').continue)
vim.keymap.set("n", "<F10>", require('dap').step_over)
vim.keymap.set("n", "<F11>", require('dap').step_into)
vim.keymap.set("n", "<F12>", require('dap').step_out)
vim.keymap.set("n", "<leader>b", require('dap').toggle_breakpoint)
-- vim.keymap.set("n", "<leader>B", require('dap').set_breakpoint(vim.fn.input('Breakpoint condition')))
-- vim.keymap.set("n", "<leader>lp", require('dap').step_out)
vim.keymap.set("n", "<leader>dr", require('dap').repl.open)
vim.keymap.set("n", "<leader>dc", require('dap').close)
